#pragma once

#ifdef RGBLIGHT_ENABLE
#define RGBLIGHT_LAYERS
#endif

#ifdef LEADER_ENABLE
#define LEADER_TIMEOUT 500
#endif

#ifdef OLED_ENABLE
#define OLED_DISPLAY_128X32
#define OLED_TIMEOUT 60000
#endif

#define IGNORE_MOD_TAP_INTERRUPT

#define TAPPING_TERM 150

#ifdef AUTO_SHIFT_ENABLE
#define AUTO_SHIFT_TIMEOUT 170
#define AUTO_SHIFT_MODIFIERS
#define NO_AUTO_SHIFT_ALPHA
#define AUTO_SHIFT_NO_AUTO_REPEAT
#endif
