version: "3.2"

services:
  cypress:
    image: "cypress/included:9.4.1"
    environment:
      CYPRESS_VIDEO: false
      CYPRESS_baseUrl: https://config.qmk.fm/#
      CYPRESS_VIEWPORT_WIDTH: 1920
      CYPRESS_VIEWPORT_HEIGHT: 1080
    working_dir: /e2e
    volumes:
      - ./cypress:/e2e
      - ./dist:/e2e/cypress/screenshots/keymap.spec.js
      - ./dist:/test_data
